# GENERATED скриптом rice — не редактировать вручную.
background #211b34
foreground #dcd9eb
selection_background #332e46
selection_foreground #dcd9eb
cursor #6da1d6
cursor_text_color #211b34
color0 #2c263e
color1 #c2886c
color2 #6da1d6
color3 #c2886c
color4 #46329d
color5 #46329d
color6 #6da1d6
color7 #7a768b
color8 #555067
color9 #c9a092
color10 #8eb1dc
color11 #c9a092
color12 #7364b4
color13 #7364b4
color14 #8eb1dc
color15 #dcd9eb
