# GENERATED скриптом rice — не редактировать вручную.
background #3f343a
foreground #f8f8f8
selection_background #51474d
selection_foreground #f8f8f8
cursor #e3adbd
cursor_text_color #3f343a
color0 #4a3f45
color1 #b8848f
color2 #b8848f
color3 #b8848f
color4 #8f8f95
color5 #e3adbd
color6 #8f8f95
color7 #979295
color8 #726a6f
color9 #cba6ae
color10 #cba6ae
color11 #cba6ae
color12 #aeaeb2
color13 #e9c3ce
color14 #aeaeb2
color15 #f8f8f8
